//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuroWiz.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CATEGORY
    {
        public M_CATEGORY()
        {
            this.T_QUIZ = new HashSet<T_QUIZ>();
        }
    
        public int CATEGORY_CD { get; set; }
        public string CATEGORY_NM { get; set; }
        public bool VISIBLE { get; set; }
    
        public virtual ICollection<T_QUIZ> T_QUIZ { get; set; }
    }
}
