//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuroWiz.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ANSWER
    {
        public int ANSWER_ID { get; set; }
        public int QUIZ_ID { get; set; }
        public int TOTAL_SEE { get; set; }
        public int CORRECT_COUNT { get; set; }
        public int FAIL_COUNT { get; set; }
    
        public virtual T_QUIZ T_QUIZ { get; set; }
    }
}
