//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuroWiz.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_QUIZ
    {
        public T_QUIZ()
        {
            this.T_ANSWER = new HashSet<T_ANSWER>();
        }
    
        public int QUIZ_ID { get; set; }
        public int CATEGORY_CD { get; set; }
        public int DIFFICULTY_CD { get; set; }
        public string SUMMARY { get; set; }
        public string C1 { get; set; }
        public string C2 { get; set; }
        public string C3 { get; set; }
        public string C4 { get; set; }
        public string ANS { get; set; }
    
        public virtual M_CATEGORY M_CATEGORY { get; set; }
        public virtual M_DIFFICULTY M_DIFFICULTY { get; set; }
        public virtual ICollection<T_ANSWER> T_ANSWER { get; set; }
    }
}
